stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion.test_size
      - data_ingestion.random_state
    outs:
      - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw
      - src/data_preprocessing.py
    outs:
      - data/interim
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/interim
    outs:
      - data/preprocessed
  model_building:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/preprocessed
    params:
      - model_building.n_estimators
      - model_building.random_state
    outs:
      - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl        
    outs:
      - reports/metrics.json